#!/usr/bin/env python
# -*- coding: utf-8 -*-
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

from setuptools import setup

setup(
    name='harry',
    description="""Harry - A Tool for Measuring String Similarity""",
    version='0.4.3',
    url='https://github.com/rieck/harry',
    author_email='konrad@mlsec.org',
    packages=['harry'],
    package_dir={'harry': 'harry'},
    classifiers=[
        "Development Status :: 0.4.3",
        "Programming Language :: Python :: 2",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: Implementation :: PyPy",
        "License :: OSI Approved :: Mozilla Public License 2.0",
    ],
    install_requires=["cffi>=1.0.0"],
    setup_requires=["cffi>=1.0.0"],
    cffi_modules=[
        "./harry/build_harry_cffi.py:ffi",
    ],
)
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
