################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

if (NOT MSVC)
    include(FindPkgConfig)
    pkg_check_modules(PC_LIBARCHIVE "libarchive")
    if (NOT PC_LIBARCHIVE_FOUND)
        pkg_check_modules(PC_LIBARCHIVE "libarchive")
    endif (NOT PC_LIBARCHIVE_FOUND)
    if (PC_LIBARCHIVE_FOUND)
        # add CFLAGS from pkg-config file, e.g. draft api.
        add_definitions(${PC_LIBARCHIVE_CFLAGS} ${PC_LIBARCHIVE_CFLAGS_OTHER})
        # some libraries install the headers is a subdirectory of the include dir
        # returned by pkg-config, so use a wildcard match to improve chances of finding
        # headers and SOs.
        set(PC_LIBARCHIVE_INCLUDE_HINTS ${PC_LIBARCHIVE_INCLUDE_DIRS} ${PC_LIBARCHIVE_INCLUDE_DIRS}/*)
        set(PC_LIBARCHIVE_LIBRARY_HINTS ${PC_LIBARCHIVE_LIBRARY_DIRS} ${PC_LIBARCHIVE_LIBRARY_DIRS}/*)
    endif(PC_LIBARCHIVE_FOUND)
endif (NOT MSVC)

find_path (
    LIBARCHIVE_INCLUDE_DIRS
    NAMES archive.h
    HINTS ${PC_LIBARCHIVE_INCLUDE_HINTS}
)

find_library (
    LIBARCHIVE_LIBRARIES
    NAMES archive
    HINTS ${PC_LIBARCHIVE_LIBRARY_HINTS}
)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(
    LIBARCHIVE
    REQUIRED_VARS LIBARCHIVE_LIBRARIES LIBARCHIVE_INCLUDE_DIRS
)
mark_as_advanced(
    LIBARCHIVE_FOUND
    LIBARCHIVE_LIBRARIES LIBARCHIVE_INCLUDE_DIRS
)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
