/*  =========================================================================
    harry - generated layer of public API

    This program is free software; you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by the  
    Free Software Foundation; either version 3 of the License, or (at your 
    option) any later version.  This program is distributed without any    
    warranty. See the GNU General Public License for more details.         

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef HARRY_LIBRARY_H_INCLUDED
#define HARRY_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>
#include <libconfig.h>
#include <zlib.h>
#if defined (HAVE_LIBARCHIVE)
#include <archive.h>
#endif
#include <math.h>

//  HARRY version macros for compile-time API detection
#define HARRY_VERSION_MAJOR 0
#define HARRY_VERSION_MINOR 4
#define HARRY_VERSION_PATCH 3

#define HARRY_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define HARRY_VERSION \
    HARRY_MAKE_VERSION(HARRY_VERSION_MAJOR, HARRY_VERSION_MINOR, HARRY_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined HARRY_STATIC
#       define HARRY_EXPORT
#   elif defined HARRY_INTERNAL_BUILD
#       if defined DLL_EXPORT
#           define HARRY_EXPORT __declspec(dllexport)
#       else
#           define HARRY_EXPORT
#       endif
#   elif defined HARRY_EXPORTS
#       define HARRY_EXPORT __declspec(dllexport)
#   else
#       define HARRY_EXPORT __declspec(dllimport)
#   endif
#   define HARRY_PRIVATE
#else
#   define HARRY_EXPORT
#   if (defined __GNUC__ && __GNUC__ >= 4) || defined __INTEL_COMPILER
#       define HARRY_PRIVATE __attribute__ ((visibility ("hidden")))
#   else
#       define HARRY_PRIVATE
#   endif
#endif

//  Project has no stable classes, so we build the draft API
#undef  HARRY_BUILD_DRAFT_API
#define HARRY_BUILD_DRAFT_API

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases
//  Draft classes are by default not built in stable releases
#ifdef HARRY_BUILD_DRAFT_API
typedef struct _util_t util_t;
#define UTIL_T_DEFINED
typedef struct _hstring_t hstring_t;
#define HSTRING_T_DEFINED
typedef struct _norm_t norm_t;
#define NORM_T_DEFINED
typedef struct _measures_t measures_t;
#define MEASURES_T_DEFINED
#endif // HARRY_BUILD_DRAFT_API


//  Public classes, each with its own header file
#ifdef HARRY_BUILD_DRAFT_API
#include "util.h"
#include "hstring.h"
#include "norm.h"
#include "measures.h"
#endif // HARRY_BUILD_DRAFT_API

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
