/*  =========================================================================
    harry_classes - private header file

    This program is free software; you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by the  
    Free Software Foundation; either version 3 of the License, or (at your 
    option) any later version.  This program is distributed without any    
    warranty. See the GNU General Public License for more details.         
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef HARRY_CLASSES_H_INCLUDED
#define HARRY_CLASSES_H_INCLUDED

//  Platform definitions, must come first
#include "platform.h"

//  External API
#include "../include/harry.h"

//  Internal API
#include "md5.h"
#include "murmur.h"
#include "rwlock.h"
#include "hconfig.h"
#include "vcache.h"
#include "hmatrix.h"
#include "kern_distance.h"
#include "kern_subsequence.h"
#include "kern_spectrum.h"
#include "kern_wdegree.h"
#include "dist_bag.h"
#include "dist_compression.h"
#include "dist_damerau.h"
#include "dist_hamming.h"
#include "dist_jarowinkler.h"
#include "dist_kernel.h"
#include "dist_lee.h"
#include "dist_levenshtein.h"
#include "dist_osa.h"
#include "sim_coefficient.h"

//  *** To avoid double-definitions, only define if building without draft ***
#ifndef HARRY_BUILD_DRAFT_API

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
HARRY_PRIVATE void
    md5_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
HARRY_PRIVATE void
    murmur_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
HARRY_PRIVATE void
    rwlock_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
HARRY_PRIVATE void
    hconfig_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
HARRY_PRIVATE void
    vcache_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
HARRY_PRIVATE void
    hmatrix_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
HARRY_PRIVATE void
    kern_distance_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
HARRY_PRIVATE void
    kern_subsequence_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
HARRY_PRIVATE void
    kern_spectrum_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
HARRY_PRIVATE void
    kern_wdegree_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
HARRY_PRIVATE void
    dist_bag_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
HARRY_PRIVATE void
    dist_compression_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
HARRY_PRIVATE void
    dist_damerau_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
HARRY_PRIVATE void
    dist_hamming_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
HARRY_PRIVATE void
    dist_jarowinkler_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
HARRY_PRIVATE void
    dist_kernel_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
HARRY_PRIVATE void
    dist_lee_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
HARRY_PRIVATE void
    dist_levenshtein_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
HARRY_PRIVATE void
    dist_osa_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
HARRY_PRIVATE void
    sim_coefficient_test (bool verbose);

//  Self test for private classes
HARRY_PRIVATE void
    harry_private_selftest (bool verbose);

#endif // HARRY_BUILD_DRAFT_API

#endif
