/*  =========================================================================
    harry_private_selftest.c - run private classes selftests

    Runs all private classes selftests.

    -------------------------------------------------------------------------
    This program is free software; you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by the  
    Free Software Foundation; either version 3 of the License, or (at your 
    option) any later version.  This program is distributed without any    
    warranty. See the GNU General Public License for more details.         

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#include "harry_classes.h"


//  -------------------------------------------------------------------------
//  Run all private classes tests.
//

void
harry_private_selftest (bool verbose)
{
// Tests for stable private classes:
    md5_test (verbose);
    murmur_test (verbose);
    rwlock_test (verbose);
    vcache_test (verbose);
    hmatrix_test (verbose);
    hconfig_test (verbose);
    kern_distance_test (verbose);
    kern_subsequence_test (verbose);
    kern_spectrum_test (verbose);
    kern_wdegree_test (verbose);
    dist_bag_test (verbose);
    dist_compression_test (verbose);
    dist_damerau_test (verbose);
    dist_hamming_test (verbose);
    dist_jarowinkler_test (verbose);
    dist_kernel_test (verbose);
    dist_lee_test (verbose);
    dist_levenshtein_test (verbose);
    dist_osa_test (verbose);
    sim_coefficient_test (verbose);
}
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
